/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.sd.kafka.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ActingEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3633714992291119644L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ActingEvent\",\"namespace\":\"com.sd.kafka.avro\",\"fields\":[{\"name\":\"actor\",\"type\":\"string\"},{\"name\":\"genre\",\"type\":\"string\"},{\"name\":\"title\",\"type\":\"string\"},{\"name\":\"timestamp\",\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ActingEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ActingEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ActingEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ActingEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ActingEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ActingEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ActingEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ActingEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ActingEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence actor;
  private java.lang.CharSequence genre;
  private java.lang.CharSequence title;
  private long timestamp;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ActingEvent() {}

  /**
   * All-args constructor.
   * @param actor The new value for actor
   * @param genre The new value for genre
   * @param title The new value for title
   * @param timestamp The new value for timestamp
   */
  public ActingEvent(java.lang.CharSequence actor, java.lang.CharSequence genre, java.lang.CharSequence title, java.lang.Long timestamp) {
    this.actor = actor;
    this.genre = genre;
    this.title = title;
    this.timestamp = timestamp;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return actor;
    case 1: return genre;
    case 2: return title;
    case 3: return timestamp;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: actor = (java.lang.CharSequence)value$; break;
    case 1: genre = (java.lang.CharSequence)value$; break;
    case 2: title = (java.lang.CharSequence)value$; break;
    case 3: timestamp = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'actor' field.
   * @return The value of the 'actor' field.
   */
  public java.lang.CharSequence getActor() {
    return actor;
  }


  /**
   * Sets the value of the 'actor' field.
   * @param value the value to set.
   */
  public void setActor(java.lang.CharSequence value) {
    this.actor = value;
  }

  /**
   * Gets the value of the 'genre' field.
   * @return The value of the 'genre' field.
   */
  public java.lang.CharSequence getGenre() {
    return genre;
  }


  /**
   * Sets the value of the 'genre' field.
   * @param value the value to set.
   */
  public void setGenre(java.lang.CharSequence value) {
    this.genre = value;
  }

  /**
   * Gets the value of the 'title' field.
   * @return The value of the 'title' field.
   */
  public java.lang.CharSequence getTitle() {
    return title;
  }


  /**
   * Sets the value of the 'title' field.
   * @param value the value to set.
   */
  public void setTitle(java.lang.CharSequence value) {
    this.title = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public long getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(long value) {
    this.timestamp = value;
  }

  /**
   * Creates a new ActingEvent RecordBuilder.
   * @return A new ActingEvent RecordBuilder
   */
  public static com.sd.kafka.avro.ActingEvent.Builder newBuilder() {
    return new com.sd.kafka.avro.ActingEvent.Builder();
  }

  /**
   * Creates a new ActingEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ActingEvent RecordBuilder
   */
  public static com.sd.kafka.avro.ActingEvent.Builder newBuilder(com.sd.kafka.avro.ActingEvent.Builder other) {
    if (other == null) {
      return new com.sd.kafka.avro.ActingEvent.Builder();
    } else {
      return new com.sd.kafka.avro.ActingEvent.Builder(other);
    }
  }

  /**
   * Creates a new ActingEvent RecordBuilder by copying an existing ActingEvent instance.
   * @param other The existing instance to copy.
   * @return A new ActingEvent RecordBuilder
   */
  public static com.sd.kafka.avro.ActingEvent.Builder newBuilder(com.sd.kafka.avro.ActingEvent other) {
    if (other == null) {
      return new com.sd.kafka.avro.ActingEvent.Builder();
    } else {
      return new com.sd.kafka.avro.ActingEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for ActingEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ActingEvent>
    implements org.apache.avro.data.RecordBuilder<ActingEvent> {

    private java.lang.CharSequence actor;
    private java.lang.CharSequence genre;
    private java.lang.CharSequence title;
    private long timestamp;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.sd.kafka.avro.ActingEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.actor)) {
        this.actor = data().deepCopy(fields()[0].schema(), other.actor);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.genre)) {
        this.genre = data().deepCopy(fields()[1].schema(), other.genre);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.title)) {
        this.title = data().deepCopy(fields()[2].schema(), other.title);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[3].schema(), other.timestamp);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing ActingEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.sd.kafka.avro.ActingEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.actor)) {
        this.actor = data().deepCopy(fields()[0].schema(), other.actor);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.genre)) {
        this.genre = data().deepCopy(fields()[1].schema(), other.genre);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.title)) {
        this.title = data().deepCopy(fields()[2].schema(), other.title);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[3].schema(), other.timestamp);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'actor' field.
      * @return The value.
      */
    public java.lang.CharSequence getActor() {
      return actor;
    }


    /**
      * Sets the value of the 'actor' field.
      * @param value The value of 'actor'.
      * @return This builder.
      */
    public com.sd.kafka.avro.ActingEvent.Builder setActor(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.actor = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'actor' field has been set.
      * @return True if the 'actor' field has been set, false otherwise.
      */
    public boolean hasActor() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'actor' field.
      * @return This builder.
      */
    public com.sd.kafka.avro.ActingEvent.Builder clearActor() {
      actor = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'genre' field.
      * @return The value.
      */
    public java.lang.CharSequence getGenre() {
      return genre;
    }


    /**
      * Sets the value of the 'genre' field.
      * @param value The value of 'genre'.
      * @return This builder.
      */
    public com.sd.kafka.avro.ActingEvent.Builder setGenre(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.genre = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'genre' field has been set.
      * @return True if the 'genre' field has been set, false otherwise.
      */
    public boolean hasGenre() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'genre' field.
      * @return This builder.
      */
    public com.sd.kafka.avro.ActingEvent.Builder clearGenre() {
      genre = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'title' field.
      * @return The value.
      */
    public java.lang.CharSequence getTitle() {
      return title;
    }


    /**
      * Sets the value of the 'title' field.
      * @param value The value of 'title'.
      * @return This builder.
      */
    public com.sd.kafka.avro.ActingEvent.Builder setTitle(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.title = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'title' field has been set.
      * @return True if the 'title' field has been set, false otherwise.
      */
    public boolean hasTitle() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'title' field.
      * @return This builder.
      */
    public com.sd.kafka.avro.ActingEvent.Builder clearTitle() {
      title = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public long getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public com.sd.kafka.avro.ActingEvent.Builder setTimestamp(long value) {
      validate(fields()[3], value);
      this.timestamp = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public com.sd.kafka.avro.ActingEvent.Builder clearTimestamp() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ActingEvent build() {
      try {
        ActingEvent record = new ActingEvent();
        record.actor = fieldSetFlags()[0] ? this.actor : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.genre = fieldSetFlags()[1] ? this.genre : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.title = fieldSetFlags()[2] ? this.title : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.timestamp = fieldSetFlags()[3] ? this.timestamp : (java.lang.Long) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ActingEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<ActingEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ActingEvent>
    READER$ = (org.apache.avro.io.DatumReader<ActingEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.actor);

    out.writeString(this.genre);

    out.writeString(this.title);

    out.writeLong(this.timestamp);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.actor = in.readString(this.actor instanceof Utf8 ? (Utf8)this.actor : null);

      this.genre = in.readString(this.genre instanceof Utf8 ? (Utf8)this.genre : null);

      this.title = in.readString(this.title instanceof Utf8 ? (Utf8)this.title : null);

      this.timestamp = in.readLong();

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.actor = in.readString(this.actor instanceof Utf8 ? (Utf8)this.actor : null);
          break;

        case 1:
          this.genre = in.readString(this.genre instanceof Utf8 ? (Utf8)this.genre : null);
          break;

        case 2:
          this.title = in.readString(this.title instanceof Utf8 ? (Utf8)this.title : null);
          break;

        case 3:
          this.timestamp = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










